name=PS2Keyboard
version=2.8
author=Christian Weichel, Paul Stoffregen, L. Abraham Smith, Cuningan
maintainer=Paul Stoffregen
sentence=Use a PS/2 Keyboard for input
paragraph=
category=Signal Input/Output
url=https://github.com/RSP365/PS2Keyboard-with-Nordic-support
architectures=*

